import { c as create_ssr_component, v as validate_component, d as each, b as add_attribute, e as escape } from "../../../chunks/ssr.js";
import { N as Navigation } from "../../../chunks/Navigation.js";
import { d as drops } from "../../../chunks/tws.js";
import { F as Fa } from "../../../chunks/fa.js";
import { faPaintBrush, faCalendarAlt } from "@fortawesome/free-solid-svg-icons/index.js";
import { B as BackToTop } from "../../../chunks/BackToTop.js";
const TogetherWeStand_svelte_svelte_type_style_lang = "";
const css = {
  code: ".tws-banner.svelte-140j79l{position:relative;width:100%;color:white;box-shadow:1px 5px 10px var(--darker-purple);border:4px transparent solid;border-radius:1rem;transition:border 0.2s ease}.rounded.svelte-140j79l{border-radius:0.75rem;width:100%;vertical-align:bottom}.unrevealed.svelte-140j79l{opacity:0.5}.tws-banner.svelte-140j79l:hover{border-color:rgb(233, 213, 255)}.tws-edition.svelte-140j79l{position:absolute;width:80%;height:80%;top:10%;left:10%;background-color:rgb(108 37 179 / 0.3);border-radius:1rem;z-index:1}.pieceTitleContainer.svelte-140j79l{height:40%;display:flex;justify-content:center;align-items:center;text-align:center;border-radius:1rem;background-color:rgb(67 18 115 / 0.6);font-size:1.25rem;padding-left:0.25rem;padding-right:0.25rem}.title.svelte-140j79l{font-size:1.5rem}.tws-grid.svelte-140j79l{height:60%;display:flex;flex-direction:column;justify-content:center;align-items:center}.tws-info.svelte-140j79l{display:flex;align-items:center;justify-content:center;column-gap:0.5rem}@media(min-width: 900px){.tws-grid.svelte-140j79l{height:60%}.tws-edition.svelte-140j79l{width:60%;height:60%;top:20%;left:20%}.title.svelte-140j79l{font-size:2rem}}@media(max-width: 500px){.tws-grid.svelte-140j79l{height:60%}.tws-edition.svelte-140j79l{width:80%;height:60%;top:20%;left:10%}.title.svelte-140j79l{font-size:1rem}.tws-info.svelte-140j79l{font-size:0.75rem}}",
  map: null
};
const TogetherWeStand = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${validate_component(Navigation, "Navigation").$$render($$result, {}, {}, {})} <section class="container"><h1 class="heading" data-svelte-h="svelte-qk7p1x">Treehouse Presents...</h1> <div class="tws-grid svelte-140j79l" data-svelte-h="svelte-19ynx77"><div><img class="rounded svelte-140j79l" src="images/tws/tws_banner.png" alt="TWS banner"></div> <br><br> <div><p class="subsectionParagraph">The Chimpions proudly present ‘Together We Stand’, a partnership with amazing artists to create small supply art editions that will elevate the artist community, empower collectors, and deepen the art / utility connection.</p> <p class="subsectionParagraph">Each edition will be created by an iconic artist or project and will depict Chimpions standing together with allies against dark forces.</p> <p class="subsectionParagraph"><strong style="font-weight: bold">Artists</strong> will be compensated for their work, receive secondary royalties, expand their reach to new audiences, be featured in promotional threads, gain support for future auctions, and gain a new community of supporters in The Treehouse, the Chimpions’ art-focused Discord channels.</p> <p class="subsectionParagraph"><strong style="font-weight: bold">Collectors</strong> will have new opportunities to collect and enjoy art from their favorite artists. Each piece will also serve as an access card with multiple layers of utility which will welcome a wider range of NFT enthusiasts to explore each edition.</p> <p class="subsectionParagraph">Read more about the vision for Together We Stand <a href="https://twitter.com/TheChimpions/status/1549412745719816197?s=20&t=FQ_D4JF10bTHVwFYWy5-Sg" target="_blank" rel="noreferrer" style="color: inherit; text-decoration: underline">here</a> or explore each edition below.</p></div></div> <h2 class="subsectionHeading" data-svelte-h="svelte-19j1s1f">Editions</h2> <div class="dropContainer">${each(drops, (drop) => {
    return `<a${add_attribute("href", `/together-we-stand/${drop.artistPath}`, 0)}><div class="tws-banner svelte-140j79l">${drop.piece.revealed === true ? `<img class="rounded svelte-140j79l"${add_attribute("src", `images/tws/${drop.piece.teaserPath}`, 0)} alt="Together We Stand Piece">` : `<img class="rounded unrevealed svelte-140j79l"${add_attribute("src", `images/tws/${drop.piece.teaserPath}`, 0)} alt="Together We Stand Piece's Teaser">`} <div class="tws-edition svelte-140j79l"><div class="pieceTitleContainer svelte-140j79l"><div class="title svelte-140j79l">${escape(drop.piece.title)}</div></div> <div class="tws-grid svelte-140j79l"><div class="tws-info svelte-140j79l"><div>${validate_component(Fa, "Fa").$$render($$result, { icon: faPaintBrush, size: "sm" }, {}, {})} ${escape(drop.artist)} </div></div> ${``} <div class="tws-info svelte-140j79l"><div>${validate_component(Fa, "Fa").$$render($$result, { icon: faCalendarAlt, size: "sm" }, {}, {})} ${escape(drop.date)}</div> </div></div> </div></div> </a>`;
  })}</div></section> ${validate_component(BackToTop, "BackToTop").$$render($$result, {}, {}, {})}`;
});
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `${validate_component(TogetherWeStand, "TogetherWeStand").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
